version: "3.5"

services:
  public-service:
    image: local/adidas-be-challenge-publicservice:latest
    container_name: adidas-be-challenge-publicservice
    build:
      context: public-service
      dockerfile: Dockerfile
    depends_on:
      - naming-server


  priority-sale-service:
    image: local/adidas-be-challenge-prioritysaleservice:latest
    container_name: adidas-be-challenge-prioritysaleservice
    build:
      context: priority-sale-service
      dockerfile: Dockerfile
    depends_on:
      - naming-server


  adiclub-service:
    image: local/adidas-be-challenge-adiclubservice:latest
    container_name: adidas-be-challenge-adiclubservice
    build:
      context: adiclub-service
      dockerfile: Dockerfile
    depends_on:
      - naming-server

  email-service:
    image: local/adidas-be-challenge-emailservice:latest
    container_name: adidas-be-challenge-emailservice
    build:
      context: email-service
      dockerfile: Dockerfile
    depends_on:
      - naming-server


  zookeeper:
    image: "bitnami/zookeeper:latest"
    container_name: "myapp-zookeeper"
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: bitnami/kafka:2.5.0
    container_name: adidas-be-challenge-kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      #- KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

  mongo:
    ports:
      - "27017:27017"
    container_name: adidas-be-challenge-mongo
    restart: always
    logging:
      options:
        max-size: 1g
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    image: mongo

  api-gateway:
    image: local/adidas-be-challenge-apigateway:latest
    container_name: adidas-be-challenge-apigateway
    build: ./api-gateway
    depends_on:
      - naming-server
    ports:
      - 9080:9080

    # Eureka Server
  naming-server:
    image: local/adidas-be-challenge-namingserver:latest
    container_name: adidas-be-challenge-namingserver
    build: ./naming-server
    ports:
      - 9061:9061
