logging:
  level:
    root: INFO
    reactor:
      netty: DEBUG
    org:
      springframework:
        cloud:
          gateway: TRACE
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://naming-server:9061/eureka}

spring:
  security:
    user:
      name: adidas
      password: adidas1234
  cloud:
    gateway:
      routes:
        - id: public-service-route
          uri: ${public-service}
          predicates:
            - Path=/public-service/**
        - id: adiclub-service-route
          uri: ${adiclub-service}
          predicates:
            - Path=/adiclub-service/**
        - id: email-service-route
          uri: ${email-service}
          predicates:
              - Path=/email-service/**
        - id: members-service-route
          uri: ${members-service}
          predicates:
              - Path=/members-service/**
        - id: openapi
          uri: http://api-gateway:${server.port}
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs
