spring:
  application:
    name: naming-server
  profiles:
    active: dev
  cloud:
    config:
      enabled: false

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: false
  server:
    maxThreadsForPeerReplication: 0

server:
  port: 9061
